CREATE TABLE NOTES (
id SERIAL PRIMARY KEY,
userId VARCHAR(50) NOT NULL,
bookId INT NOT NULL,
bookTitle VARCHAR(256) NOT NULL,
creationDate DATE DEFAULT CURRENT_DATE NOT NULL,
noteTitle VARCHAR(256) NOT NULL,
noteText VARCHAR(1000) NOT NULL
);