CREATE TABLE BOOKS (
id SERIAL PRIMARY KEY,
userId VARCHAR(50) NOT NULL,
title VARCHAR(256) NOT NULL,
author VARCHAR(256) NOT NULL,
numberOfPages INT NOT NULL,
currentPage INT NOT NULL,
startDate DATE DEFAULT CURRENT_DATE NOT NULL,
finishDate DATE,
currentlyReading BOOLEAN NOT NULL
);